version: '3.8'

services:
  pokemon-mcp-ingestion:
    build:
      context: .
      dockerfile: packages/pokemon-mcp-ingestion/Dockerfile
    container_name: pokemon-ingestion
    volumes:
      - pokemon_data:/app/data
    environment:
      - NODE_ENV=production
    networks:
      - pokemon_network
    profiles:
      - ingestion

  pokemon-mcp-server:
    build:
      context: .
      dockerfile: packages/pokemon-mcp-server/Dockerfile
    container_name: pokemon-server
    volumes:
      - pokemon_data:/app/data
    environment:
      - NODE_ENV=production
    depends_on:
      - pokemon-mcp-ingestion
    networks:
      - pokemon_network
    profiles:
      - server
    stdin_open: true
    tty: true

  # Development services
  pokemon-mcp-server-dev:
    build:
      context: .
      dockerfile: packages/pokemon-mcp-server/Dockerfile
    container_name: pokemon-server-dev
    volumes:
      - pokemon_data:/app/data
      - ./packages/pokemon-mcp-server:/app/packages/pokemon-mcp-server
      - /app/packages/pokemon-mcp-server/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev
    networks:
      - pokemon_network
    profiles:
      - dev
    stdin_open: true
    tty: true

  pokemon-mcp-ingestion-dev:
    build:
      context: .
      dockerfile: packages/pokemon-mcp-ingestion/Dockerfile
    container_name: pokemon-ingestion-dev
    volumes:
      - pokemon_data:/app/data
      - ./packages/pokemon-mcp-ingestion:/app/packages/pokemon-mcp-ingestion
      - /app/packages/pokemon-mcp-ingestion/node_modules
    environment:
      - NODE_ENV=development
      - POKEMON_LIMIT=50
    command: pnpm dev
    networks:
      - pokemon_network
    profiles:
      - dev

volumes:
  pokemon_data:

networks:
  pokemon_network:
    driver: bridge