packages:
  - packages/*

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

catalog:
  # Runtime dependencies
  "@modelcontextprotocol/sdk": "^0.5.0"
  "better-sqlite3": "^9.4.3"
  "node-fetch": "^3.3.2"
  
  # Dev dependencies
  "@types/better-sqlite3": "^7.6.9"
  "@types/node": "^20.11.30"
  "tsx": "^4.7.1"
  "typescript": "^5.4.2"
  "prettier": "^3.0.0"
  "husky": "^8.0.0"
  "lint-staged": "^15.0.0"
  "vitest": "^1.5.0"